on:
  push:
    branches: [yeet]
  pull_request:
    branches: [yeet]

name: "ZNS build"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog backend
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: latest
      - uses: actions/checkout@v2
      - name: build binary
        working-directory: ./zns-server
        run: swipl --goal=main --stand_alone=true -o zns -c main.pl
